export enum BUTTON_CLASS_OPTIONS {
    INFO = 'INFO',
    DANGER = 'DANGER',
    SUCCESS = 'SUCCESS',
    OUTLINE = 'OUTLINE',
    SUCCESS_BORDERED_OUTLINE = 'SUCCESS_BORDERED_OUTLINE',
    DANGER_BORDERED_OUTLINE = 'DANGER_BORDERED_OUTLINE',
    BORDERED_OUTLINE = 'BORDERED_OUTLINE',
}