export const question_static_texts: Record<string, string> = {
    createNewAnswer: 'ارسال پاسخ',
    writeYourAnswer: 'پاسخ خود را بنویسید',
    answers: 'پاسخ ها',
    answerWasBad: 'پاسخ خوب نبود',
    answerWasGood: 'پاسخ خوب بود',
    answerIsMandatory: 'پاسخ الزامی است',
    subject: 'موضوع',
    description: 'متن سوال',
    createNewQuestion: 'ایجاد سوال جدید',
    cancel: 'انصراف',
    create: 'ایجاد سوال',
    subjectIsMandatory: 'موضوع اجباری است',
    descriptionIsMandatory: 'متن سوال اجباری است',
    seeDetail: 'مشاهده جزییات',
}